server:
    port: 8084
spring: 
    application: 
        name: crudconfig
    cloud: 
      config: 
        server: 
          git:
            uri: https://github.com/SandwichBiscuit/test.git